# Generated by Django 2.2.7 on 2019-12-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='isFavorite',
            field=models.BooleanField(default=False),
        ),
    ]
